---
version: "2"

run:
  timeout: 10m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

severity:
  default: error
