---
version: "2"

run:
  timeout: 10m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

severity:
  default: error