name: Bug Report
description: File a bug report to help us improve KubeFTPd
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - rossigee

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: KubeFTPd Version
      description: What version of KubeFTPd are you running?
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: kubernetes-version
    attributes:
      label: Kubernetes Version
      description: What version of Kubernetes are you using?
      placeholder: v1.28.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running KubeFTPd in?
      options:
        - Local development (Docker Compose)
        - Local Kubernetes (Kind/Minikube)
        - Cloud Kubernetes (EKS/GKE/AKS)
        - On-premise Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what should have happened!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Deploy KubeFTPd with...
        2. Create User CRD with...
        3. Connect FTP client...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant logs from KubeFTPd controller
      placeholder: |
        kubectl logs -n kubeftpd-system deployment/kubeftpd-controller-manager
      render: shell

  - type: textarea
    id: manifests
    attributes:
      label: Kubernetes Manifests
      description: Relevant CRD manifests (User, MinioBackend, WebDavBackend)
      placeholder: |
        apiVersion: ftp.golder.org/v1
        kind: User
        ...
      render: yaml

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
