apiVersion: ftp.golder.org/v1
kind: MinioBackend
metadata:
  labels:
    app.kubernetes.io/name: kubeftpd
    app.kubernetes.io/managed-by: kustomize
  name: miniobackend-sample
spec:
  # TODO(user): Add fields here
