apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeftpd.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeftpd.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubeftpd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        {{- include "kubeftpd.labels" . | nindent 8 }}
        app.kubernetes.io/component: manager
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "kubeftpd.serviceAccountName" . }}
      {{- with .Values.controller.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.controller.securityContext | nindent 8 }}
      containers:
      - name: manager
        image: {{ include "kubeftpd.controller.image" . }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        {{- if .Values.controller.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        env:
        - name: FTP_PORT
          value: {{ .Values.ftp.service.port | quote }}
        - name: FTP_PASSIVE_PORT_MIN
          value: {{ .Values.ftp.passive.service.portRange.min | quote }}
        - name: FTP_PASSIVE_PORT_MAX
          value: {{ .Values.ftp.passive.service.portRange.max | quote }}
        - name: FTP_WELCOME_MESSAGE
          value: {{ .Values.ftp.settings.welcomeMessage | quote }}
        - name: FTP_IDLE_TIMEOUT
          value: {{ .Values.ftp.settings.idleTimeout | quote }}
        - name: FTP_MAX_CONNECTIONS
          value: {{ .Values.ftp.settings.maxConnections | quote }}
        {{- if .Values.controller.metrics.enabled }}
        - name: METRICS_PORT
          value: "8080"
        {{- end }}
        - name: HEALTH_PORT
          value: "8081"
        ports:
        - containerPort: {{ .Values.ftp.service.port }}
          name: ftp
          protocol: TCP
        {{- if .Values.ftp.passive.enabled }}
        {{- range $port := untilStep (int .Values.ftp.passive.service.portRange.min) (int (add .Values.ftp.passive.service.portRange.max 1)) 1 }}
        - containerPort: {{ $port }}
          name: passive-{{ $port }}
          protocol: TCP
        {{- end }}
        {{- end }}
        - containerPort: 8081
          name: health
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.controller.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controller.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.controller.securityContext | nindent 10 }}
      {{- if .Values.controller.metrics.enabled }}
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.18.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
