# Monitoring and Alerting for KubeFTPd Password Security
# Prometheus rules and Grafana dashboards for password management

---
# PrometheusRule for password security monitoring
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubeftpd-password-security
  namespace: kubeftpd-system
  labels:
    app: kubeftpd
    component: security-monitoring
spec:
  groups:
  - name: kubeftpd.password.security
    interval: 30s
    rules:
    
    # Count users with plaintext passwords
    - record: kubeftpd:users_plaintext_password_total
      expr: |
        count by (namespace) (
          kube_customresource_info{
            customresource_group="ftp.golder.org",
            customresource_kind="User",
            customresource_version="v1"
          } * on (namespace, name) group_left()
          label_replace(
            kube_customresource{
              customresource_group="ftp.golder.org",
              customresource_kind="User",
              customresource_version="v1",
              jsonpath="{.spec.password}"
            } != "", "has_plaintext", "1", "", ""
          )
        ) or vector(0)
    
    # Count users with secret-based passwords
    - record: kubeftpd:users_secret_password_total
      expr: |
        count by (namespace) (
          kube_customresource_info{
            customresource_group="ftp.golder.org",
            customresource_kind="User",
            customresource_version="v1"
          } * on (namespace, name) group_left()
          label_replace(
            kube_customresource{
              customresource_group="ftp.golder.org",
              customresource_kind="User", 
              customresource_version="v1",
              jsonpath="{.spec.passwordSecret.name}"
            } != "", "has_secret", "1", "", ""
          )
        ) or vector(0)
    
    # Authentication failure rate
    - record: kubeftpd:auth_failure_rate_5m
      expr: |
        rate(kubeftpd_auth_failures_total[5m])
    
    # Secret access errors
    - record: kubeftpd:secret_access_errors_5m
      expr: |
        rate(kubeftpd_secret_access_errors_total[5m])

  - name: kubeftpd.password.alerts
    rules:
    
    # Alert on plaintext passwords in production
    - alert: KubeFTPdPlaintextPasswordsInProduction
      expr: |
        kubeftpd:users_plaintext_password_total > 0
        and on (namespace) kube_namespace_labels{label_environment="production"}
      for: 0m
      labels:
        severity: critical
        component: kubeftpd
        security_risk: high
      annotations:
        summary: "KubeFTPd users with plaintext passwords detected in production"
        description: |
          {{ $value }} FTP users in namespace {{ $labels.namespace }} are using 
          plaintext passwords in a production environment. This is a security risk.
          Please migrate to secret-based passwords immediately.
        runbook_url: "https://docs.kubeftpd.io/security/password-migration"
    
    # Alert on high authentication failure rate
    - alert: KubeFTPdHighAuthFailureRate
      expr: kubeftpd:auth_failure_rate_5m > 0.1
      for: 2m
      labels:
        severity: warning
        component: kubeftpd
      annotations:
        summary: "High FTP authentication failure rate"
        description: |
          FTP authentication failure rate is {{ $value | humanizePercentage }} 
          over the last 5 minutes. This could indicate:
          - Brute force attacks
          - Misconfigured passwords or secrets
          - Application integration issues
    
    # Alert on secret access errors
    - alert: KubeFTPdSecretAccessErrors
      expr: kubeftpd:secret_access_errors_5m > 0
      for: 1m
      labels:
        severity: critical
        component: kubeftpd
      annotations:
        summary: "KubeFTPd cannot access password secrets"
        description: |
          KubeFTPd is experiencing errors accessing password secrets at a rate of 
          {{ $value }} errors per second. Check RBAC permissions and secret availability.
    
    # Alert on missing password secrets
    - alert: KubeFTPdMissingPasswordSecret
      expr: |
        kubeftpd_user_secret_missing > 0
      for: 30s
      labels:
        severity: critical
        component: kubeftpd
      annotations:
        summary: "FTP user password secret is missing"
        description: |
          User {{ $labels.username }} in namespace {{ $labels.namespace }} 
          references password secret {{ $labels.secret_name }} which does not exist.
    
    # Alert on weak password patterns (if metrics are available)
    - alert: KubeFTPdWeakPasswordDetected
      expr: kubeftpd_weak_passwords_total > 0
      for: 0m
      labels:
        severity: warning
        component: kubeftpd
        security_risk: medium
      annotations:
        summary: "Weak FTP passwords detected"
        description: |
          {{ $value }} FTP users have been detected with weak passwords. 
          Consider implementing stronger password policies.

---
# ServiceMonitor for KubeFTPd metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeftpd-password-metrics
  namespace: kubeftpd-system
  labels:
    app: kubeftpd
    component: password-monitoring
spec:
  selector:
    matchLabels:
      app: kubeftpd
      component: server
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    # Focus on password and authentication metrics
    - sourceLabels: [__name__]
      regex: "kubeftpd_(auth|password|secret).*"
      action: keep

---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeftpd-password-dashboard
  namespace: kubeftpd-system
  labels:
    grafana_dashboard: "1"
data:
  kubeftpd-password-security.json: |
    {
      "dashboard": {
        "id": null,
        "title": "KubeFTPd Password Security",
        "tags": ["kubeftpd", "security", "passwords"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Password Security Overview",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(kubeftpd:users_secret_password_total)",
                "legendFormat": "Secret-based Users"
              },
              {
                "expr": "sum(kubeftpd:users_plaintext_password_total)", 
                "legendFormat": "Plaintext Users"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": 0},
                    {"color": "yellow", "value": 1},
                    {"color": "red", "value": 5}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Authentication Failure Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "kubeftpd:auth_failure_rate_5m",
                "legendFormat": "Auth Failures/sec"
              }
            ],
            "yAxes": [
              {
                "label": "Failures per second",
                "min": 0
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Secret Access Errors",
            "type": "graph", 
            "targets": [
              {
                "expr": "kubeftpd:secret_access_errors_5m",
                "legendFormat": "Secret Errors/sec"
              }
            ],
            "alert": {
              "conditions": [
                {
                  "query": {"params": ["A", "1m", "now"]},
                  "reducer": {"params": [], "type": "last"},
                  "evaluator": {"params": [0], "type": "gt"}
                }
              ],
              "executionErrorState": "alerting",
              "for": "1m",
              "frequency": "10s",
              "handler": 1,
              "name": "Secret Access Errors",
              "noDataState": "no_data"
            },
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          }
        ],
        "time": {"from": "now-1h", "to": "now"},
        "refresh": "30s"
      }
    }