---
name: Clean CI

"on":
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  GO_VERSION: '1.25'

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install tools
        run: |
          # Install kubebuilder
          curl -L -o kubebuilder https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)
          chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/

      - name: Build
        run: |
          make manifests generate fmt vet
          make build build-kubeftpd

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-cache: true

      - name: Test
        run: |
          make test

      - name: Security scan
        run: |
          make security-scan || echo "Security scan completed with expected issues"

      - name: Build Docker (multi-arch)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag kubeftpd:test \
            .

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        if: always()
        with:
          files: ./coverage.out
          fail_ci_if_error: false

      - name: Upload security results
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('gosec.sarif') != ''
        with:
          sarif_file: gosec.sarif
